insert into skill (name)
values
    ('CSS (Cascading Style Sheets)'),
    ('XML (Extensible Markup Language)'),
    ('Oracle PL/SQL'),
    ('SPICE (Simulation Program with Integrated Circuit Emphasis)'),
    ('Vue.js'),
    ('Java'),
    ('iOS'),
    ('PROC SQL'),
    ('SAP'),
    ('Concepts (C++)'),
    ('HTML5 (HyperText Markup Language 5)'),
    ('Adobe After Effects (Ae)'),
    ('Vegas Pro'),
    ('DaVinci Resolve'),
    ('Adobe XD (Xd)'),
    ('ProtoPie'),
    ('InVision'),
    ('Justinmind'),
    ('Framer'),
    ('1backend'),
    ('ActionHero.js'),
    ('ActionScript'),
    ('Active Admin'),
    ('ActiveCampaign'),
    ('Acunote'),
    ('AddThis'),
    ('Adobe Bridge (Br)'),
    ('Adobe Dreamweaver (Dw)'),
    ('Adobe Fuse (Fs)'),
    ('Adobe Illustrator (Ai)'),
    ('Adobe InCopy (Ic)'),
    ('Adobe InDesign (Id)'),
    ('Adobe Lightroom (Lr)'),
    ('Adobe Photoshop (Ps)'),
    ('Adobe Premiere Pro (Pr)'),
    ('AdRoll'),
    ('Adobe Experience Manager (AEM)'),
    ('Aerobatic'),
    ('Aerospike'),
    ('Affinity Designer'),
    ('AFNetworking'),
    ('Airpal'),
    ('Ajax'),
    ('Akka.NET'),
    ('Alamofire'),
    ('Altibase'),
    ('Amazon API Gateway'),
    ('Amazon AppStream'),
    ('Amazon Athena'),
    ('Amazon Aurora'),
    ('Amazon Chime'),
    ('Amazon CloudFront'),
    ('Amazon CloudWatch'),
    ('Amazon Cognito'),
    ('Amazon Comprehend'),
    ('Amazon Connect'),
    ('Amazon DynamoDB'),
    ('Amazon Elastic Compute Cloud (EC2)'),
    ('Amazon Elastic Container Registry (ECR)'),
    ('Amazon Elastic Container Service (ECS)'),
    ('Amazon Elastic Kubernetes Service (EKS)'),
    ('Amazon Elastic Block Store (EBS)'),
    ('Amazon Elastic File System (EFS)'),
    ('Amazon Elastic Transcoder'),
    ('Amazon ElastiCache'),
    ('Amazon EMR'),
    ('AWS FreeRTOS'),
    ('Amazon Inspector'),
    ('Amazon Kinesis'),
    ('Amazon Lex'),
    ('Amazon Lightsail'),
    ('Amazon Macie'),
    ('Amazon Mechanical Turk (MTurk)'),
    ('Amazon MQ'),
    ('Amazon Neptune'),
    ('Amazon Pinpoint'),
    ('Amazon Polly'),
    ('Amazon QuickSight'),
    ('Amazon Redshift'),
    ('Amazon Relational Database Service (RDS)'),
    ('Amazon Route 53'),
    ('Amazon SageMaker'),
    ('Amazon Simple Notification Service (SNS)'),
    ('Amazon Simple Queue Service (SQS)'),
    ('Amazon SimpleDB'),
    ('Amazon Sumerian'),
    ('Amazon Virtual Private Cloud (VPC)'),
    ('AWS (Amazon Web Services)'),
    ('Amazon WorkSpaces'),
    ('Amazon WorkDocs'),
    ('amCharts'),
    ('Ampersand.js'),
    ('Amplitude'),
    ('Anaconda'),
    ('Android'),
    ('Android Room'),
    ('Android SDK'),
    ('Android Studio'),
    ('Angular Material'),
    ('AngularJS'),
    ('AngularUI'),
    ('Animate.css'),
    ('Ansible'),
    ('ANSYS'),
    ('Ant Design'),
    ('AnyChart'),
    ('Apache Accmulo'),
    ('Apache ActiveMQ'),
    ('Apache Airflow'),
    ('Apache Allura'),
    ('Apache Ant'),
    ('Apache Any23'),
    ('Apache Apisix'),
    ('Apache Archiva'),
    ('Apache Aries'),
    ('Apache Arrow'),
    ('Apache AsterixDB'),
    ('Apache Aurora'),
    ('Apache Avro'),
    ('Apache Axis'),
    ('Apache Beam'),
    ('Apache Bigtop'),
    ('Apache BookKeeper'),
    ('Apache Brooklyn'),
    ('Apache Buildr'),
    ('Apache Bval'),
    ('Apache Calcite'),
    ('Apache Camel'),
    ('Apache CarbonData'),
    ('Apache Cassandra'),
    ('Apache Cayenne'),
    ('Apache Celix'),
    ('Apache Chemistry'),
    ('Apache Chukwa'),
    ('Apache CloudStack'),
    ('Apache Cordova'),
    ('Apache CouchDB'),
    ('Apache Crunch'),
    ('Apache cTAKES'),
    ('Apache CXF'),
    ('Apache DataFu'),
    ('Apache Drill'),
    ('Apache Druid'),
    ('Apache Empire-db'),
    ('Apache Felix'),
    ('Apache Fineract'),
    ('Apache Flex'),
    ('Apache Flink'),
    ('Apache Fluo'),
    ('Apache Forrest'),
    ('Apache FreeMarker'),
    ('Apache Geode'),
    ('Apache Geronimo'),
    ('Apache Griffin'),
    ('Apache Groovy'),
    ('Apache Guacamole'),
    ('Amazon GuardDuty'),
    ('Apache Gump'),
    ('Apache Hadoop'),
    ('Apache HAWQ'),
    ('Apache HBase'),
    ('Apache Helix'),
    ('Apache Hive'),
    ('Apache HTTP Server'),
    ('Apache Ignite'),
    ('Apache Impala'),
    ('Apache Isis'),
    ('Apache Jackrabbit'),
    ('Apache James'),
    ('Apache jclouds'),
    ('Apache Jena'),
    ('Apache JMeter'),
    ('Apache JSPWiki'),
    ('Apache jUDDI'),
    ('Apache Juneau'),
    ('Apache Kafka'),
    ('Apache Karaf'),
    ('Apache Kibble'),
    ('Apache Knox'),
    ('Apache Kudu'),
    ('Apache Kylin'),
    ('Apache Lens'),
    ('Apache Libcloud'),
    ('Apache Logging'),
    ('Apache Lucene'),
    ('Lucene.Net'),
    ('Apache Mahout'),
    ('Apache Maven'),
    ('Apache Mesos'),
    ('Apache MINA'),
    ('Apache Mnemonic'),
    ('Apache MXNet'),
    ('Apache MyFaces'),
    ('Apache Mynewt'),
    ('Apache NiFi'),
    ('Apache Nutch'),
    ('Apache OFBiz'),
    ('Apache Olingo'),
    ('Apache OODT'),
    ('Apache Oozie'),
    ('Apache OpenJPA'),
    ('Apache OpenMeetings'),
    ('Apache OpenNLP'),
    ('Apache OpenOffice (AOO)'),
    ('Apache OpenWebBeans'),
    ('Apache OpenWhisk'),
    ('Apache PDFBox'),
    ('Apache Phoenix'),
    ('Apache Pig'),
    ('Apache Pivot'),
    ('Apache POI'),
    ('Apache Pulsar'),
    ('Apache Qpid'),
    ('Apache Ranger'),
    ('Apache REEF'),
    ('Apache River'),
    ('Apache RocketMQ'),
    ('Apache Roller'),
    ('Apache Royale'),
    ('Apache Samza'),
    ('Apache Santuario'),
    ('Apache Sentry'),
    ('Apache Shiro'),
    ('Apache SIS'),
    ('Apache Sling'),
    ('Apache Solr'),
    ('Apache SpamAssassin'),
    ('Apache Spark'),
    ('Apache Storm'),
    ('Apache Struts'),
    ('Apache Superset'),
    ('Apache Synapse'),
    ('Apache Syncope'),
    ('Apache SystemDS'),
    ('Apache Tapestry'),
    ('Apache Tez'),
    ('Apache Thrift'),
    ('Apache Tomcat'),
    ('Apache TomEE'),
    ('Apache Turbine'),
    ('Apache UIMA'),
    ('Apache Unomi'),
    ('Apache Usergrid'),
    ('Apache VCL'),
    ('Apache Velocity'),
    ('Apache Wicket'),
    ('Apache Xalan'),
    ('Apache Xerces'),
    ('Apache XML Graphics'),
    ('Apache XMLBeans'),
    ('Apache Yetus'),
    ('Apache Zeppelin'),
    ('Apache ZooKeeper'),
    ('Apex Ping'),
    ('API Blueprint'),
    ('API Star'),
    ('API Umbrella'),
    ('Dialogflow'),
    ('Apiary API Flow'),
    ('Apify SDK'),
    ('Apigee API'),
    ('Apigility'),
    ('Apollo'),
    ('Apollo Server'),
    ('App Annie'),
    ('MIT App Inventor'),
    ('Appcelerator'),
    ('AppDynamics'),
    ('AppsFlyer'),
    ('AppHarbor'),
    ('Appium'),
    ('Apple HealthKit'),
    ('Applitools'),
    ('AppScale'),
    ('Apptimize'),
    ('Appveyor'),
    ('aptly'),
    ('Aqueduct'),
    ('ArangoDB'),
    ('ArcGIS'),
    ('ArcMap'),
    ('ARCore'),
    ('Arcus'),
    ('Ardoq'),
    ('Argo CD'),
    ('ARKit'),
    ('ARM'),
    ('Armeria'),
    ('Armory'),
    ('Asana'),
    ('Asciinema'),
    ('asm.js'),
    ('ASN.1 (Abstract Syntax Notation One)'),
    ('ASP (Active Server Pages)'),
    ('ASP.NET'),
    ('Assembly Language'),
    ('AssemblyAI'),
    ('Cirrus Insight'),
    ('Astronomer'),
    ('Atatus'),
    ('ATL (Active Template Library)'),
    ('Atlantis'),
    ('ATLAS.ti'),
    ('MongoDB Atlas'),
    ('Atlassian Bamboo'),
    ('ATmega128 Firmware'),
    ('Atmel AVR'),
    ('Atmosphere'),
    ('Atom'),
    ('Atomic'),
    ('Atomic CSS'),
    ('Atom IDE'),
    ('AudioKit'),
    ('AUIGrid'),
    ('Aura'),
    ('Aurelia'),
    ('Authy'),
    ('Autodesk AutoCAD'),
    ('Autodesk 3ds Max'),
    ('Autodesk Maya'),
    ('SeeControl'),
    ('AutoHotKey'),
    ('AutopilotHQ'),
    ('AUTOSAR'),
    ('opsZero'),
    ('AVA'),
    ('Avalonia'),
    ('Avocado'),
    ('Avocode'),
    ('AVX-512'),
    ('awless'),
    ('Amazon Alexa Skills Kit SDK'),
    ('AWS Amplify'),
    ('AWS AppSync'),
    ('AWS Artifact'),
    ('AWS Auto Scaling'),
    ('AWS Backup'),
    ('AWS Budgets'),
    ('AWS Certificate Manager (ACM)'),
    ('AWS CLI (CLI)'),
    ('AWS Cloud Development Kit (CDK)'),
    ('AWS CloudFormation'),
    ('AWS CloudHSM'),
    ('AWS CloudTrail'),
    ('AWS CodeBuild'),
    ('AWS CodeCommit'),
    ('AWS CodeDeploy'),
    ('AWS CodePipeline'),
    ('AWS CodeStar'),
    ('AWS Config'),
    ('AWS Control Tower'),
    ('AWS Cost Explorer'),
    ('Amazon Data Pipeline'),
    ('AWS Database Migration Service (DMS)'),
    ('AWS Device Farm (DF)'),
    ('AWS Direct Connect (DC)'),
    ('Amazon DocumentDB'),
    ('AWS Elastic Beanstalk'),
    ('Amazon Elastic Load Balancing (ELB)'),
    ('AWS Elemental MediaConvert'),
    ('AWS Elemental MediaLive'),
    ('AWS Elemental MediaPackage'),
    ('AWS Elemental MediaStore'),
    ('AWS Fargate'),
    ('Amazon Forecast'),
    ('Amazon FSx'),
    ('AWS Global Accelerator'),
    ('AWS Glue'),
    ('AWS Ground Station'),
    ('AWS IAM'),
    ('AWS IoT 1-Click'),
    ('AWS IoT Core'),
    ('AWS IoT Device Defender'),
    ('AWS IoT Device Management'),
    ('AWS IoT Events'),
    ('AWS IoT Greengrass'),
    ('AWS IoT SiteWise'),
    ('AWS IoT Things Graph'),
    ('AWS Key Management Service (KMS)'),
    ('AWS Lambda'),
    ('AWS License Manager'),
    ('Amazon Managed Blockchain'),
    ('AWS Elemental MediaConnect'),
    ('AWS Elemental MediaTailor'),
    ('AWS Migration Hub'),
    ('AWS Mobile Hub'),
    ('Amazon Managed Streaming for Apache Kakfa (MSK)'),
    ('AWS OpsWorks'),
    ('AWS Organizations'),
    ('AWS Personal Health Dashboard (PHD)'),
    ('Amazon Personalize'),
    ('Amazon Rekognition'),
    ('AWS Resource Access Manager (RAM)'),
    ('AWS RoboMaker'),
    ('Amazon Simple Storage Service (S3)'),
    ('Amazon S3 Glacier'),
    ('AWS Security Hub'),
    ('AWS Service Catalog'),
    ('AWS CloudShell'),
    ('AWS Shield'),
    ('Amazon Simple Email Service (SES)'),
    ('AWS Single Sign-On (SSO)'),
    ('AWS Snowball Edge'),
    ('AWS Step Functions'),
    ('AWS Storage Gateway'),
    ('Amazon Simple Workflow Service (SWF)'),
    ('AWS Systems Manager (SSM)'),
    ('Amazon Textract'),
    ('Amazon Transcribe'),
    ('AWS Transfer Family'),
    ('Amazon Translate'),
    ('AWS Trusted Advisor'),
    ('AWS WAF'),
    ('AWS Well-Architected Tool'),
    ('Amazon WorkLink'),
    ('Amazon WorkMail'),
    ('AWX'),
    ('Axios'),
    ('Axure RP'),
    ('AYLIEN'),
    ('Microsoft Azure'),
    ('Azure Active Directory (AD)'),
    ('Azure Active Directory B2C (AD B2C)'),
    ('Azure Active Directory Domain Services (AD DS)'),
    ('Azure Advisor'),
    ('Azure Application Gateway'),
    ('Azure Archive Storage'),
    ('Azure Automation'),
    ('Azure Avere vFXT for Azure'),
    ('Azure Bing Autosuggest API'),
    ('Azure Bing Custom Search API'),
    ('Azure Bing Entity Search API'),
    ('Azure Bing Image Search API'),
    ('Azure Bing News Search API'),
    ('Azure Bing Spell Check API'),
    ('Azure Bing Video Search API'),
    ('Azure Bing Visual Search API'),
    ('Azure Bing Web Search API'),
    ('Azure Blob Storage'),
    ('Azure Blueprints'),
    ('Azure Bot Service'),
    ('Azure Cache for Redis'),
    ('Azure Cloud Shell'),
    ('Azure Cognitive Search'),
    ('Azure Cognitive Services'),
    ('Azure Computer Vision'),
    ('Azure Container Instances'),
    ('Azure Content Delivery Network (CDN)'),
    ('Azure Content Moderator'),
    ('Azure Content Protection'),
    ('Azure Cosmos DB'),
    ('Azure Custom Vision'),
    ('Azure CycleCloud'),
    ('Azure Data Box'),
    ('Azure Data Catalog'),
    ('Azure Data Explorer'),
    ('Azure Data Lake Analytics'),
    ('Azure Data Lake Storage (ADLS)'),
    ('Azure Data Science Virtual Machines (DSVM)'),
    ('Azure Database for MariaDB'),
    ('Azure Database for PostgreSQL'),
    ('Azure Databricks'),
    ('Azure Dedicated HSM'),
    ('Azure DevOps Server'),
    ('Azure Digital Twins'),
    ('Azure DNS'),
    ('Azure Encoding'),
    ('Azure Event Grid'),
    ('Azure Event Hubs'),
    ('Azure ExpressRoute'),
    ('Azure Face API'),
    ('Azure Files'),
    ('Azure Firewall'),
    ('Azure Functions'),
    ('Azure HDInsight'),
    ('Azure Information Protection (AIP)'),
    ('Azure IoT Hub'),
    ('Azure IoT Central'),
    ('Azure Key Vault'),
    ('Azure Kinect Developer Kit (DK)'),
    ('Azure Kubernetes Service (AKS)'),
    ('Azure Conversational Language Understanding (LUIS)'),
    ('Azure Linux Virtual Machines (VM)'),
    ('Azure Live and On-Demand Streaming'),
    ('Azure Load Balancer'),
    ('Azure Logic Apps'),
    ('Azure Machine Learning'),
    ('Azure Media Player'),
    ('Azure Media Services'),
    ('Azure Microsoft Genomics'),
    ('Azure Microsoft Portal'),
    ('Azure Migrate'),
    ('Azure Mobile Apps'),
    ('Azure Monitor'),
    ('Azure Database for MySQL'),
    ('Azure NetApp Files (ANF)'),
    ('Azure Network Watcher'),
    ('Azure Notification Hubs'),
    ('Azure Pipelines'),
    ('Azure Power BI Embedded'),
    ('Azure QnA Maker'),
    ('Azure Queue Storage'),
    ('Azure R Server for HDInsight'),
    ('Azure SAP Solutions'),
    ('Azure Sercurity Center'),
    ('Azure Service Bus'),
    ('Azure SignalR Service'),
    ('Azure Site Recovery (ASR)'),
    ('Azure Spatial Anchors'),
    ('Azure Speaker Recognition'),
    ('Azure Speech to Text'),
    ('Azure Speech Translation'),
    ('Azure Sphere'),
    ('Azure SQL Data Warehouse (SQL DW)'),
    ('Azure Storage'),
    ('Azure Storage Explorer'),
    ('Azure Stream Analytics'),
    ('Azure Synapse Analytics'),
    ('Azure Table Storage'),
    ('Azure Text Analytics'),
    ('Azure Text to Speech'),
    ('Azure Time Series Insights'),
    ('Azure Translator'),
    ('Azure Video Analyzer'),
    ('Azure Virtual Machine Scale Sets (VMSS)'),
    ('Azure Virtual Machines (VM)'),
    ('Azure Virtual Network (VNet)'),
    ('Azure Virtual WAN'),
    ('Azure VPN Gateway'),
    ('Azure Web App for Containers'),
    ('Azure Windows 10 IoT Core Services'),
    ('Azure Xamarin'),
    ('BabylonJS'),
    ('backbone.js'),
    ('back-end'),
    ('Balsamiq'),
    ('Basecamp'),
    ('Bash'),
    ('Bazel'),
    ('Beanstalk'),
    ('BeautifulSoup'),
    ('BSD (Berkeley Software Distribution)'),
    ('Bespoken Tools'),
    ('Big Data'),
    ('billboard.js'),
    ('BinTray'),
    ('BitBar'),
    ('Bitbucket'),
    ('Bitnami'),
    ('Bitrise'),
    ('bitwarden'),
    ('Bixby'),
    ('Blackfire.io'),
    ('BlazeMeter'),
    ('Blender'),
    ('Blockchain'),
    ('Blogger'),
    ('Bluebird'),
    ('BlueZ'),
    ('Boost'),
    ('Boot camp'),
    ('Boot2Docker'),
    ('Bootstrap'),
    ('Bootstrap Studio'),
    ('Bosun'),
    ('Botkit'),
    ('Boto3'),
    ('Botpress'),
    ('Bottle'),
    ('Boundary'),
    ('Bourbon'),
    ('Bower'),
    ('Box'),
    ('Brackets'),
    ('Braintree'),
    ('Branch Metrics'),
    ('Browserify'),
    ('BrowserStack'),
    ('Brunch'),
    ('Buddybuild'),
    ('Buffer'),
    ('BugHerd'),
    ('Bugzilla'),
    ('Buildkite'),
    ('BulkSMS'),
    ('C'),
    ('C#'),
    ('C++'),
    ('C3.js'),
    ('Cachet'),
    ('Cacti'),
    ('Cactus'),
    ('CADKEY'),
    ('CADRA'),
    ('Cafe24 API'),
    ('Caffe'),
    ('Cage'),
    ('CakePHP'),
    ('Calendly'),
    ('CameraTag'),
    ('Campaign Monitor'),
    ('Canvas'),
    ('CanvasJS'),
    ('Capistrano'),
    ('CAPL (Communication Access Programming Language)'),
    ('Capybara'),
    ('Caret'),
    ('CarrierWave'),
    ('Carthage'),
    ('CARTO'),
    ('Castle'),
    ('Castor'),
    ('caver-js'),
    ('CDAP'),
    ('cdnjs'),
    ('Celery'),
    ('CentOS'),
    ('Ceph'),
    ('CesiumJS'),
    ('Chai'),
    ('Chalice'),
    ('Chaplin.js'),
    ('Chargify'),
    ('Charles'),
    ('Chart.js'),
    ('Chartio'),
    ('ChartMogul'),
    ('Chatfuel'),
    ('Chatlio'),
    ('Chatscript'),
    ('Chef'),
    ('Chromium Embedded Framework (CEF)'),
    ('CircleCI'),
    ('Circuit'),
    ('Citus'),
    ('Clair'),
    ('Clara Labs'),
    ('Classy'),
    ('Claudia'),
    ('ClearDB'),
    ('Clickhouse'),
    ('Clicky'),
    ('CSR (Client Side Rendering)'),
    ('Clion'),
    ('Clojure'),
    ('ClojureScript'),
    ('Google Closure Tools'),
    ('Google Cloud Client Library'),
    ('Cloud 66'),
    ('Cloud Foundry (CF)'),
    ('Cloud Functions for Firebase'),
    ('AWS Cloud9'),
    ('CloudAMQP'),
    ('Cloudant'),
    ('CloudBees'),
    ('CloudCheckr'),
    ('Cloudera Data Platform (CDP)'),
    ('Cloudmailin'),
    ('COBOL'),
    ('CockroachDB'),
    ('Cocoa Touch'),
    ('Cocoa'),
    ('CocoaLumberjack'),
    ('CocoaPods'),
    ('Cocos2d'),
    ('Codacy'),
    ('Code Climate'),
    ('Codeanywhere'),
    ('Codeception'),
    ('Codecov'),
    ('CodeFactor'),
    ('Codefresh'),
    ('CodeIgniter'),
    ('CodeKit'),
    ('CodeMirror'),
    ('CodePush'),
    ('CodeSandbox'),
    ('Codeship'),
    ('Codio'),
    ('CoffeeScript'),
    ('Coinbase'),
    ('collectd'),
    ('Common Lisp (CL)'),
    ('Compass'),
    ('Composer'),
    ('Conan'),
    ('Concourse CI'),
    ('Atlassian Confluence'),
    ('Constant Contact'),
    ('Consul'),
    ('CNI (Container Network Interface)'),
    ('Contentful'),
    ('Continuous'),
    ('Coralogix'),
    ('Cosmos sdk'),
    ('Couchbase'),
    ('Countly'),
    ('Coveralls'),
    ('Coverity Scan'),
    ('Cowboy'),
    ('Cozimo'),
    ('cPanel'),
    ('CPLEX'),
    ('Craft'),
    ('Crazy Egg'),
    ('Credo'),
    ('Creolabs'),
    ('Crisp'),
    ('VMware Workspace ONE'),
    ('Cronitor'),
    ('Cronjob'),
    ('Cronofy'),
    ('Atlassian Crucible'),
    ('Crystal'),
    ('Ctop'),
    ('CUBRID'),
    ('Cuckoo Sandbox'),
    ('Cucumber'),
    ('CUDA'),
    ('cURL'),
    ('Customer.io'),
    ('CycleJs'),
    ('Cyclotron'),
    ('Cyfe'),
    ('Cypress'),
    ('D'),
    ('D3.JS'),
    ('Dagger'),
    ('DalmatinerDB'),
    ('Dancer'),
    ('Dapper ORM'),
    ('monday.com'),
    ('Dart'),
    ('Dashbird'),
    ('Dashlane'),
    ('DPDK (Data Plane Development Kit)'),
    ('IBM Data Studio'),
    ('Database Labs'),
    ('Android DataBinding'),
    ('Datadog'),
    ('DataGrip'),
    ('DataHero'),
    ('Datomic'),
    ('DCHQ'),
    ('Debian'),
    ('Deco'),
    ('DeepGit'),
    ('DeepLinkDispatch'),
    ('deepstream.io'),
    ('Dejavu'),
    ('Delayed::Job'),
    ('Delighted'),
    ('Tidelift'),
    ('Deployd'),
    ('Deployer'),
    ('Detectify'),
    ('HelixTeamHub'),
    ('Devise'),
    ('DevOps'),
    ('DevSpace'),
    ('DHTMLX'),
    ('diff-so-fancy'),
    ('DiffableDataSources'),
    ('Diffbot'),
    ('DigitalOcean'),
    ('DigitalOcean Block Storage'),
    ('DigitalOcean Load Balancer'),
    ('DigitalOcean Spaces'),
    ('Dimensions CM'),
    ('Dimple.js'),
    ('Directus'),
    ('Discord'),
    ('Discourse'),
    ('Disqus'),
    ('Djangae'),
    ('Django'),
    ('Django Channels'),
    ('Django ORM'),
    ('Django REST Framework'),
    ('DL4J (Deeplearning4j)'),
    ('Dlib'),
    ('DocGen'),
    ('Dockbit'),
    ('Docker'),
    ('Docker Hub'),
    ('Docker Compose'),
    ('Docker Datacenter'),
    ('Docker Machine'),
    ('Docker Swarm'),
    ('Docker Swarm Visualizer'),
    ('DocPad'),
    ('Docparser'),
    ('Docsify'),
    ('Doctrine 2'),
    ('Docusaurus'),
    ('DodgerCMS'),
    ('Dokku'),
    ('Doodle'),
    ('Doorbell.io'),
    ('DotCi'),
    ('dotmesh'),
    ('더존 아이큐브 (Douzone iCUBE)'),
    ('더존 스마트 A (Douzone Smart A)'),
    ('dozeo'),
    ('Draggable JS'),
    ('Dramatiq'),
    ('Drift'),
    ('Drift Developer Platform'),
    ('Drip'),
    ('Drone.io'),
    ('Dropbox'),
    ('Dropmark'),
    ('Dropwizard'),
    ('Drupal'),
    ('Dumb-init'),
    ('Durandal'),
    ('Dust.js'),
    ('Dwolla'),
    ('EAGLE Cad'),
    ('EarlGrey'),
    ('EasyPost'),
    ('Apache ECharts'),
    ('Echo'),
    ('Eclipse'),
    ('Eclipse Che'),
    ('ES (ECMAScript)'),
    ('EdgeCast'),
    ('Eel'),
    ('eGovFrame'),
    ('Ehcache'),
    ('EJS (Easy Java Simulations)'),
    ('Elasticsearch'),
    ('ElasticBox'),
    ('Electron'),
    ('Electron Toolkit'),
    ('Electron.NET'),
    ('Element'),
    ('Elemental UI'),
    ('ElephantSQL'),
    ('Elev.io'),
    ('Elixir'),
    ('ELK (Elasticsearch, Logstash, Kibana)'),
    ('Elm'),
    ('Emacs'),
    ('emacs-slack'),
    ('Email on Acid'),
    ('EmailHooks'),
    ('EmailListVerify'),
    ('EmbedBox'),
    ('EJS (Embedded JavaScript)'),
    ('Ember FastBoot'),
    ('Ember.js'),
    ('Emotion'),
    ('Empire'),
    ('Clarabridge'),
    ('Engine Yard Cloud'),
    ('Entity Framework'),
    ('Entry'),
    ('Envkey'),
    ('Envoyer'),
    ('Enzyme'),
    ('Epoch by Fastly'),
    ('Erbit'),
    ('Erlang'),
    ('Errorception'),
    ('ESLint'),
    ('Espresso.js'),
    ('Eta'),
    ('etcd'),
    ('ethers.js'),
    ('Ethereum'),
    ('Eucalyptus'),
    ('Eve'),
    ('EventQL'),
    ('Exceptiontrap'),
    ('eXo Platform'),
    ('ExoPlayer'),
    ('ExpeditedSSL'),
    ('Expensify'),
    ('Expo'),
    ('ExpressJS'),
    ('XHTML'),
    ('Ext JS'),
    ('F#'),
    ('F.lux'),
    ('Fabric'),
    ('Twitter Fabric'),
    ('Hyperledger Fabric SDK'),
    ('fabric8'),
    ('Facebook API'),
    ('Facebook Pixel'),
    ('Facebook Prophet'),
    ('Falcon'),
    ('FastAPI'),
    ('Fastify'),
    ('Fastlane'),
    ('Fastly'),
    ('Fat-Free'),
    ('FeathersJS'),
    ('Fedora Linux'),
    ('Figma'),
    ('FCM (Firebase Cloud Messaging)'),
    ('Firebird'),
    ('Flask'),
    ('Flat UI'),
    ('Fluentd'),
    ('Flutter'),
    ('Flux'),
    ('Flyway'),
    ('Font Awesome'),
    ('Fork'),
    ('Forms API'),
    ('Formata'),
    ('Formstack'),
    ('fortrabbit'),
    ('FORTRAN'),
    ('FOSSA'),
    ('Fossil'),
    ('Elastic Cloud'),
    ('Foundation'),
    ('Foundation for Apps'),
    ('Framebench'),
    ('Framework7'),
    ('Franchise'),
    ('Frappe Charts'),
    ('Freeboard'),
    ('FreeBSD'),
    ('FreeRDP'),
    ('Frenzy'),
    ('FreshDesk'),
    ('Front'),
    ('Fstar'),
    ('FuelPHP'),
    ('FullContact'),
    ('Fullstory'),
    ('Furan'),
    ('FxJS'),
    ('gaia'),
    ('Galileo'),
    ('Gallium'),
    ('GameBryo'),
    ('Ganache CLI'),
    ('Gandi'),
    ('Ganglia'),
    ('Gatling'),
    ('Gatsby'),
    ('GatsbyJS'),
    ('Gauge'),
    ('Gauges'),
    ('GDScript'),
    ('Geany'),
    ('Gearman'),
    ('Geckoboard'),
    ('GeddyJS'),
    ('Gelato.io'),
    ('Gemfury'),
    ('Gemnasium'),
    ('GPGPU (General Purpose computing on GPU)'),
    ('Gensim'),
    ('GeoServer'),
    ('GDAL (Geospatial Data Abstraction Library)'),
    ('Gerrit'),
    ('Get Satisfaction'),
    ('Flow'),
    ('getMetrics'),
    ('Scaleform GFx'),
    ('Ghost'),
    ('Ghost Inspector'),
    ('Gin Web Framework'),
    ('Git'),
    ('Git Reflow'),
    ('Git-appraise'),
    ('Gitblit'),
    ('Gitboard'),
    ('Gitcolony'),
    ('GitCop'),
    ('git-dit'),
    ('Gitea'),
    ('Gitential'),
    ('GitHub'),
    ('Github Action'),
    ('GitHub Native'),
    ('GitKraken'),
    ('Gitkube'),
    ('GitLab'),
    ('GitLab CI/CD'),
    ('GitLab Pages'),
    ('Gitless'),
    ('GitLocalize'),
    ('GitMonitor'),
    ('GitNotifier'),
    ('Gitolite'),
    ('GitOps'),
    ('GitPoint'),
    ('Gitql'),
    ('Git-Repo'),
    ('GitSavvy'),
    ('git-sizer'),
    ('gitsome'),
    ('Gleam'),
    ('Glide'),
    ('Glimmer.js'),
    ('Glitch'),
    ('Gluon'),
    ('GlusterFS'),
    ('gnuboard'),
    ('Go'),
    ('Go CD'),
    ('goa'),
    ('go-chart'),
    ('gockerize'),
    ('GoConvey'),
    ('Godot Engine'),
    ('AWS GoFormation'),
    ('go-git'),
    ('Gogs'),
    ('GoLand'),
    ('GoodData'),
    ('Google AdSense'),
    ('Google Cloud AI Hub'),
    ('Google Cloud AI Platform'),
    ('Google Analytics'),
    ('Google Cloud Apigee Health APIx'),
    ('Google Cloud Apigee Open Banking APIx'),
    ('Google Cloud Apigee Sense'),
    ('Google Cloud App Engine'),
    ('Google Apps Script'),
    ('Google Cloud BigQuery'),
    ('Google Cloud Binary Authorization'),
    ('Google Cloud AutoML'),
    ('Google Cloud Bigtable'),
    ('Google Cloud Build'),
    ('Google Cloud CDN'),
    ('Google Cloud Container Builder'),
    ('Google Cloud Data Loss Prevention'),
    ('Google Cloud Dataflow'),
    ('Google Cloud Datalab'),
    ('Google Cloud Dataprep'),
    ('Google Cloud Dataproc'),
    ('Google Cloud Datastore'),
    ('Google Cloud Deep Learning VM Image'),
    ('Google Cloud Deployment Manager'),
    ('Google Cloud Endpoints'),
    ('Google Cloud Filestore'),
    ('Google Cloud Functions'),
    ('Google Cloud HSM'),
    ('Google Cloud Identity and Access Management (IAM)'),
    ('Google Cloud Identity-Aware Proxy (IAP)'),
    ('Google Cloud IoT Core'),
    ('Google Cloud IoT Edge'),
    ('Google Cloud Memorystore'),
    ('Google Cloud Messaging'),
    ('Google Cloud Mobile App'),
    ('Google Cloud Natural Language AI'),
    ('GCP (Google Cloud Platform)'),
    ('Google Cloud Pub/Sub'),
    ('Google Cloud Scheduler'),
    ('Google Cloud SDK'),
    ('Google Cloud Security Command Center'),
    ('Google Cloud Shell'),
    ('Google Cloud Source Repositories'),
    ('Google Cloud Spanner'),
    ('Google Cloud Speech-to-Text'),
    ('Google Cloud SQL'),
    ('Google Cloud SQL for PostgreSQL'),
    ('Google Cloud Storage (GCS)'),
    ('Google Cloud Storage for Firebase'),
    ('Google Cloud Talent Solution'),
    ('Google Cloud Firebase Test Lab'),
    ('Google Cloud Tools for Eclipse'),
    ('Google Cloud Tools for IntelliJ'),
    ('Google Cloud Tools for PowerShell'),
    ('Google Cloud TPU'),
    ('Google Cloud Video Intelligence AI'),
    ('Google Cloud Vision AI'),
    ('Google Cloud Compute Engine'),
    ('Google Cloud Container Registry'),
    ('Google Cost Management'),
    ('Google Cloud Anthos Config Management'),
    ('Google Cloud Dialogflow'),
    ('Google Docs'),
    ('Google Drive'),
    ('Google Cloud Error Reporting'),
    ('Google Firebase Crashlytics'),
    ('Google Firebase Performance Monitoring'),
    ('Google Firebase Predictions'),
    ('Google Firebase Realtime Database'),
    ('Google Firebase Firestore'),
    ('Google Geolocation API'),
    ('Google Kubernetes Engine (GKE)'),
    ('Google Gradle App Engine Plugin'),
    ('Google Cloud Graphics Processing Units (GPUs)'),
    ('Google Guice'),
    ('Google Hangouts'),
    ('Google Cloud Istio on GKE'),
    ('Google Knative'),
    ('Google Cloud Logging'),
    ('Google Cloud Monitoring'),
    ('Google Persistent Disk'),
    ('Google Play Game Service'),
    ('Google Cloud Private Catalog'),
    ('Google Cloud Profiler'),
    ('GRR (Google Rapid Response)'),
    ('Google Cloud Resource Manager'),
    ('Google Titan Security Key'),
    ('Google Sheets'),
    ('Google Cloud Shielded VMs'),
    ('Google Stackdriver'),
    ('Google Workspace'),
    ('Google Tag Manager'),
    ('Google Cloud Titan Security Key'),
    ('Google Cloud Trace'),
    ('Google Cloud Velostrata'),
    ('Google Cloud VPC Service Controls'),
    ('Google Cloud Zync Render'),
    ('gopass'),
    ('GoSquared'),
    ('GoTTY'),
    ('GoVisually'),
    ('GPUImage'),
    ('Gradle'),
    ('Grafana'),
    ('Grails'),
    ('Grape'),
    ('Grapevine Village'),
    ('Microsoft Graph Engine (GE)'),
    ('Graph Story'),
    ('GraphCMS'),
    ('Graphcool Framework'),
    ('Graphene'),
    ('GrapheneDB'),
    ('GraphicsMagick'),
    ('GraphiQL'),
    ('Graphite'),
    ('Turi Create'),
    ('Graphol'),
    ('GraphQL'),
    ('GraphQL Voyager'),
    ('Grasshopper 3D'),
    ('Gravit Designer PRO'),
    ('Teleport'),
    ('Graylog'),
    ('Greenhouse'),
    ('Greenplum Database'),
    ('Hiver'),
    ('Gridbox'),
    ('GrooveHQ'),
    ('gRPC'),
    ('Grunt'),
    ('GRV (Git Repository Viewer)'),
    ('Gson'),
    ('GStreamer'),
    ('Google Guava'),
    ('gulp.js'),
    ('Gumby Framework'),
    ('gun'),
    ('Gunicorn'),
    ('Gunnery'),
    ('Gupshup'),
    ('Gusto'),
    ('GVFS (GNOME Virtual File System)'),
    ('H2 Database'),
    ('H2O.ai'),
    ('Chef Habitat'),
    ('Habitus'),
    ('Hack'),
    ('Hackpad'),
    ('Hadolint (Haskell Dockerfile Linter)'),
    ('Haiku'),
    ('HAML (HTML Abstraction Markdup Language)'),
    ('Hanami'),
    ('Handlebars.js'),
    ('Handsontable'),
    ('hapi'),
    ('Happyfox'),
    ('HHVM (HipHop Virtual Machine)'),
    ('Hibernate'),
    ('High Voltage'),
    ('HighchartsJS'),
    ('Highrise'),
    ('Hipache'),
    ('HipChat'),
    ('HiRDB'),
    ('HiveQL'),
    ('HLSL (High Level Shader Language)'),
    ('Hogan.js'),
    ('Honeybadger'),
    ('Honeycomb'),
    ('Hoodie'),
    ('Horizon'),
    ('Hosted Graphite'),
    ('Hotjar'),
    ('Hound'),
    ('Hound by Etsy'),
    ('HubCommander'),
    ('HuBoard'),
    ('Hubot'),
    ('HubPress'),
    ('HubSpot'),
    ('Huddle'),
    ('Hudson'),
    ('Hug'),
    ('Hugo'),
    ('Humongous.io'),
    ('Hund'),
    ('Hutch'),
    ('Hyperapp'),
    ('Hyperledger'),
    ('Hyperstack'),
    ('HTML (HyperText Markup Language)'),
    ('HTTP (HyperText Transfer Protocol)'),
    ('HTTPS (HyperText Transfer Protocol over Secure Socket Layer)'),
    ('Hypervisor'),
    ('Hystrix'),
    ('i''mport'),
    ('IBM AIX'),
    ('IBM Cloud'),
    ('IBM Cognos Analytics'),
    ('IBM Containers'),
    ('IBM DataStage'),
    ('IBM Db2'),
    ('IBM HPC Solution'),
    ('IBM SPSS Amos'),
    ('IBM Swift Sandbox'),
    ('IBM Watson APIs'),
    ('IBM WebSphere Application Server'),
    ('iContact'),
    ('iD3'),
    ('IDA Pro'),
    ('IDoneThis'),
    ('TerrSet'),
    ('Iframely'),
    ('IFTTT'),
    ('Imagify'),
    ('imgix'),
    ('Immer'),
    ('Immutable.js'),
    ('import.io'),
    ('Incapsula'),
    ('inDinero'),
    ('IMU (Inertial Measurement Unit)'),
    ('Infer'),
    ('InfluxDB'),
    ('IBM Informix'),
    ('Init.ai'),
    ('Insight.io for Github'),
    ('Insightly'),
    ('Insomnia REST Client'),
    ('Inspectlet'),
    ('Inspeqtor'),
    ('Instainer'),
    ('Instant 2FA'),
    ('Instapage'),
    ('Instrumental'),
    ('Intel MKL'),
    ('IntelliJ IDEA'),
    ('Interactable'),
    ('Interana'),
    ('Intercom'),
    ('IoT (Internet of Things)'),
    ('io.js'),
    ('ioBroker'),
    ('Ionic'),
    ('iPadOS'),
    ('IPFS (InterPlanetary File System)'),
    ('ipinfo.io'),
    ('ipTables'),
    ('Iris'),
    ('Iron'),
    ('IronMQ'),
    ('IronWorker'),
    ('issue.sh'),
    ('Istio'),
    ('ITIL (Information Technology Infrastructure Library)'),
    ('Iterable'),
    ('ITK (Insight ToolKit)'),
    ('iwantmyname'),
    ('J2ObjC'),
    ('Jabbix'),
    ('JADE (Java Agent Development Framework)'),
    ('Jaeger'),
    ('Jandi'),
    ('Janus WebRTC Server'),
    ('Jasmine'),
    ('JDBC (Java DataBase Connectivity)'),
    ('JDK (Java Development Kit)'),
    ('JMS (Java Message Service)'),
    ('JOOQ (Java Object Oriented Querying)'),
    ('JPA (Java Persistence API)'),
    ('JSP (Java Server Page)'),
    ('JSTL (JAVA Server page standard Tag Library)'),
    ('Java Swing'),
    ('JVM (Java Virtual Machine)'),
    ('JavaFX'),
    ('Javalin'),
    ('Javascript'),
    ('JBoss'),
    ('Jekyll'),
    ('Jelastic'),
    ('Jell'),
    ('Jenkins'),
    ('Jest'),
    ('Jetpack'),
    ('Jetty'),
    ('JFace'),
    ('Jinja'),
    ('Atlassian JIRA'),
    ('JitPack'),
    ('Jive Social Intranet'),
    ('JMP'),
    ('JNI (Java Native Interface)'),
    ('Join.me'),
    ('Jolie'),
    ('Jolteon'),
    ('Joomla!'),
    ('Joyent Cloud'),
    ('Joyent Triton'),
    ('jQuery'),
    ('jQuery Mobile'),
    ('jQuery UI'),
    ('Jruby'),
    ('JS Beautifier'),
    ('jsblocks'),
    ('Jscrambler'),
    ('JSDelivr'),
    ('JSDoc'),
    ('JSF (Jakarta Server Faces)'),
    ('JSON Server'),
    ('JSON Web Token'),
    ('JSONlite'),
    ('Jsoup'),
    ('JSS (Javascript Style Sheet)'),
    ('JSX'),
    ('Julia'),
    ('Jungle'),
    ('Junit'),
    ('JUniversal'),
    ('Jupyter'),
    ('K8Guard'),
    ('Kadira'),
    ('Kafka Manager'),
    ('Kairos API'),
    ('KairosDB'),
    ('Kakao Map API'),
    ('Kakao Vision API'),
    ('Kakao Link API'),
    ('Kakao Moment API'),
    ('Kakao Navi API'),
    ('Kakao Pay API'),
    ('Kakao Story API'),
    ('Kakao Talk'),
    ('Kakao Talk API'),
    ('Kakao Work'),
    ('Kakoune'),
    ('Kaldi'),
    ('Kantree'),
    ('Karma'),
    ('Karyon'),
    ('Katalon Studio'),
    ('Kayako'),
    ('Keen IO'),
    ('Kemal'),
    ('Kendo UI'),
    ('Kepware'),
    ('Keras'),
    ('Keratin AuthN'),
    ('Kestrel'),
    ('Keybase Teams'),
    ('KeyCDN'),
    ('KeystoneJS'),
    ('Kibana'),
    ('Kickbox'),
    ('Kinto'),
    ('Kinvey'),
    ('Kite'),
    ('Kitematic'),
    ('Kivy'),
    ('Klaytn'),
    ('Kloudless'),
    ('Knack'),
    ('Knex.js'),
    ('KnockoutJS'),
    ('Koa.js'),
    ('Kobra.io'),
    ('Koding'),
    ('Kohana'),
    ('Koin'),
    ('Komodo IDE'),
    ('Kompose'),
    ('Kong'),
    ('KoNLPy'),
    ('KOps'),
    ('Kore'),
    ('Kotlin'),
    ('Kraken.io'),
    ('KSQL'),
    ('Ktor'),
    ('Kube-Bench'),
    ('KubeDB'),
    ('Kubeflow'),
    ('Kubeless'),
    ('Kubernetes (K8S)'),
    ('Kue'),
    ('National Instruments LabVIEW'),
    ('LambCI'),
    ('LambdaNative'),
    ('Lander'),
    ('Laravel'),
    ('Laravel Forge'),
    ('Laravel Spark'),
    ('LastPass'),
    ('Lateral'),
    ('LaTex'),
    ('Launchaco'),
    ('LaunchDarkly'),
    ('LaunchKit'),
    ('Launchrock'),
    ('LaunchTrack'),
    ('Leaf'),
    ('Leaflet'),
    ('LESS (Leaner Style Sheets)'),
    ('LeanLabs Kanban'),
    ('Leanplum'),
    ('Leftronic'),
    ('lelylan'),
    ('LessAccounting'),
    ('Let''s Chat'),
    ('Librato'),
    ('librosa'),
    ('libseccomp'),
    ('Liferay'),
    ('Lift Framework'),
    ('LightGBM'),
    ('lighttpd'),
    ('Lineman'),
    ('Linkerd'),
    ('Linkurious'),
    ('Linode'),
    ('Linux'),
    ('Linux Crontab'),
    ('Linux Kernel'),
    ('LinuxKit'),
    ('Liquibase'),
    ('Lisp'),
    ('Lit'),
    ('Lita'),
    ('LiteDB'),
    ('Live Charts'),
    ('LiveChat'),
    ('LiveFyre'),
    ('Loader.io'),
    ('Lob'),
    ('LocalStack'),
    ('Localytics'),
    ('Locust'),
    ('Lodash'),
    ('Logback'),
    ('LogDNA'),
    ('Logentries'),
    ('Loggly'),
    ('LogicMonitor'),
    ('LogRocket'),
    ('Logstash'),
    ('LogTrail'),
    ('LokiJS'),
    ('Lookback'),
    ('Loopback'),
    ('Lottie'),
    ('Lovefield'),
    ('Lua'),
    ('Luigi'),
    ('Lumen'),
    ('Lyrebird'),
    ('Mac OS'),
    ('Macaron'),
    ('MacDown'),
    ('MacGap'),
    ('MLOps'),
    ('Mad Mimi'),
    ('Magento'),
    ('MailChimp'),
    ('Mailform'),
    ('Mailinator'),
    ('Mailit'),
    ('Mailjet'),
    ('Mailparser'),
    ('MailSlurp'),
    ('Mailtrain'),
    ('Mailtrap'),
    ('Mailigen'),
    ('Mandrill'),
    ('Mantis Bug Tracker'),
    ('Mapbox'),
    ('MapReduce'),
    ('MAPS.ME'),
    ('Marathon'),
    ('MariaDB'),
    ('Marionette'),
    ('Markdown'),
    ('Marketo'),
    ('MarkLogic'),
    ('Marko'),
    ('Markup'),
    ('Marmalade SDK'),
    ('Marp'),
    ('Martini'),
    ('Marvel'),
    ('MassiveJS'),
    ('Matcha'),
    ('Material'),
    ('Material Design for AngularJS Apps'),
    ('Material Design for Bootstrap'),
    ('Material Design Lite'),
    ('Material Kit'),
    ('Materialize'),
    ('Matetial UI'),
    ('MathWorks MATLAB'),
    ('Matplotlib'),
    ('Matter'),
    ('Mattermost'),
    ('Mavo'),
    ('Maze'),
    ('McRouter'),
    ('MEAN.JS'),
    ('Meatier'),
    ('Medium'),
    ('Meetings.io'),
    ('Meistertask'),
    ('Memcached'),
    ('Memcached Cloud'),
    ('MemCachier'),
    ('Memsource'),
    ('Mention'),
    ('Mercurial'),
    ('Message.io'),
    ('MessageBird'),
    ('Metabase'),
    ('Metalsmith'),
    ('MetaMask'),
    ('MeteorJS'),
    ('Metricbeat'),
    ('MetricsGraphics.js'),
    ('Metro Bundler'),
    ('Meya'),
    ('MFC (Microsoft Foundation Class Library)'),
    ('Micro'),
    ('micro:bit'),
    ('Microbundle'),
    ('Micronaut'),
    ('Microsoft Bot Framework'),
    ('Microsoft Excel'),
    ('Hyper-V'),
    ('Microsoft IIS (Internet Information Service)'),
    ('Microsoft Office'),
    ('Microsoft Powerpoint'),
    ('Microsoft SQL Server (MSSQL)'),
    ('Microsoft Teams'),
    ('Microsoft Visual Basic'),
    ('Microsoft Visual C++'),
    ('Microsoft Word'),
    ('Middleman'),
    ('Middleware'),
    ('Milligram'),
    ('Minio'),
    ('Mirage JS'),
    ('MireDot'),
    ('Mithril'),
    ('Mixmax'),
    ('Mixpanel'),
    ('ML Kit'),
    ('MLflow'),
    ('MobX'),
    ('Mocha'),
    ('MockFlow'),
    ('Mockingbird'),
    ('Mockito'),
    ('Modern PHP'),
    ('Modernizr'),
    ('NVIDIA Modulus'),
    ('Mojolicious'),
    ('Moment.js'),
    ('Monaco Editor'),
    ('Monkberry'),
    ('MonetDB'),
    ('MongoDB'),
    ('MongoDB Stitch'),
    ('Mongoid'),
    ('mLab'),
    ('Mongoose'),
    ('Mongoose Web Server'),
    ('MonkeyLearn'),
    ('MoonMail'),
    ('Morpheus'),
    ('Mouseflow'),
    ('Moxtra'),
    ('Mozilla Brick'),
    ('MPAndroidChart'),
    ('mPDF'),
    ('MPEG-DASH'),
    ('Microsoft Build Engine'),
    ('Multi Router Traffic Grapher'),
    ('Munin'),
    ('Mustache'),
    ('MyBatis'),
    ('Mycli'),
    ('MySQL'),
    ('Nachos UI'),
    ('Nagios'),
    ('Nancy'),
    ('NanoNets'),
    ('Android NDK'),
    ('NativeBase'),
    ('Nativefier'),
    ('NativeScript'),
    ('NATS'),
    ('NLTK (Natural Language Toolkit)'),
    ('Naver Open API'),
    ('NCP (Naver Cloud Platform)'),
    ('Naver Works'),
    ('ncurses'),
    ('Nemo.js'),
    ('Neo4j'),
    ('Neos CMS'),
    ('Neovim'),
    ('NervJS'),
    ('NestJS'),
    ('NetBeans IDE'),
    ('Netbeast'),
    ('Zuul'),
    ('Netlify'),
    ('NetSuite'),
    ('Netty'),
    ('NetworkX'),
    ('Neutronium'),
    ('NeverBounce'),
    ('New Relic'),
    ('Nexacro'),
    ('Vonage'),
    ('Next.js'),
    ('NGINX'),
    ('NGINX Amplify'),
    ('NGINX Unit'),
    ('nGrinder'),
    ('ngrok'),
    ('NgRx'),
    ('Nicereply'),
    ('Nightwatchjs'),
    ('Apache NMS'),
    ('Nodal.js'),
    ('npm (Node Package Manager)'),
    ('Node.js'),
    ('NodeFly'),
    ('Nodejitsu'),
    ('Node-RED'),
    ('Nomad'),
    ('Notion'),
    ('Notism'),
    ('NS1'),
    ('NSIS'),
    ('NSML'),
    ('NSQ'),
    ('Numpy'),
    ('Nutcache'),
    ('Nuxt.js'),
    ('NVIDIA TensorRT'),
    ('OAuth'),
    ('OAuth.io'),
    ('Obfuscation'),
    ('Objective-C'),
    ('Ocaml'),
    ('Octane AI'),
    ('OctoberCMS'),
    ('Octobox'),
    ('OctoDNS'),
    ('Octopress'),
    ('Octopus Deploy'),
    ('Octotree'),
    ('OOXML (Office OPEN XML)'),
    ('Oh Dear!'),
    ('OK Log'),
    ('OkHttp'),
    ('Okta'),
    ('Olark'),
    ('OmniDB'),
    ('OneLogin'),
    ('OneSignal'),
    ('OneSky'),
    ('Onfleet'),
    ('Onsen UI'),
    ('OpenAPI'),
    ('OpenGL (Open Graphic Library)'),
    ('Open PostgreSQL Monitoring (OPM)'),
    ('OSGi (Open Service Gateway Initiative)'),
    ('Open Audio Library (OpenAL)'),
    ('OpenCL (Open Computing Language)'),
    ('OpenCV (Open Source Computer Vision)'),
    ('OpenEBS'),
    ('OpenFace'),
    ('openflow13'),
    ('OpenGL ES (OpenGL for Embedded Systems)'),
    ('GLSL(OpenGL Shading Language)'),
    ('OpenH264'),
    ('OpenID'),
    ('OpenID Connect'),
    ('OpenLayers'),
    ('OpenMP (Open Multi Processing)'),
    ('openpyxl'),
    ('OpenResty'),
    ('OpenSceneGraph'),
    ('Red Hat OpenShift'),
    ('OpenSSL'),
    ('OpenStack'),
    ('OpenStreetMap'),
    ('OpenTok'),
    ('OpenTracing'),
    ('OpenVINO'),
    ('OpenVPN'),
    ('OpenWeatherMap'),
    ('OpsDash'),
    ('OpsGenie'),
    ('Optimizely'),
    ('Ora'),
    ('Oracle Database (RDBMS)'),
    ('Oracle Forms'),
    ('Oracle WebLogic Server'),
    ('OrCAD'),
    ('Orchard Core'),
    ('Origami'),
    ('Orleans'),
    ('OSEK'),
    ('osquery'),
    ('Otto'),
    ('OutSystems'),
    ('Overflow.io'),
    ('Overlay'),
    ('OverOps'),
    ('OVH'),
    ('Pachyderm'),
    ('Packer'),
    ('Network Packet'),
    ('packgecloud.io'),
    ('Padrino'),
    ('Page2Images'),
    ('Pagedraw'),
    ('PagerDuty'),
    ('Pandas'),
    ('Pantheon'),
    ('Papertrail'),
    ('Parcel'),
    ('Parse'),
    ('ParseHub'),
    ('Parse Server'),
    ('Pascal'),
    ('Phusion Passenger'),
    ('Passport.js'),
    ('pathogen.vim'),
    ('Patroni'),
    ('Paw'),
    ('PayPal'),
    ('peewee'),
    ('Pelican'),
    ('Pelikan'),
    ('Pencil'),
    ('Pentaho'),
    ('Perfect Audience'),
    ('Perforce'),
    ('Periscope'),
    ('Perl'),
    ('PersistlQ'),
    ('PHP (Hypertext Preprocessor)'),
    ('pganalyze'),
    ('pgcli'),
    ('Phabricator'),
    ('Phalcon'),
    ('PhantomJS'),
    ('Phaser'),
    ('Phoenix'),
    ('PhysX'),
    ('Pingdom'),
    ('Pipedrive'),
    ('PlatformIO'),
    ('Play Framework'),
    ('Playwright'),
    ('PLC (Programmable Logic Controller)'),
    ('Plotly'),
    ('Podio'),
    ('Polymer'),
    ('PopSQL'),
    ('Portainer'),
    ('C POSIX Library'),
    ('Postal'),
    ('PostCSS'),
    ('PostGIS'),
    ('PostGraphile'),
    ('PostgreSQL'),
    ('Postico'),
    ('Postman'),
    ('Postmark'),
    ('Pouchdb'),
    ('PowerShell'),
    ('Preact'),
    ('Precursor'),
    ('Prerender'),
    ('PrestaShop'),
    ('Presto'),
    ('Prettier'),
    ('PrimeFaces'),
    ('Prisma'),
    ('Prismic'),
    ('ProcessWire'),
    ('Prolog'),
    ( 'Prometheus'),
    ( 'Prototype JavaScript Framework'),
    ( 'Protractor'),
    ( 'PUBG API'),
    ( 'PubNub'),
    ( 'Pug'),
    ( 'Puppet'),
    ( 'Puppeteer'),
    ( 'Pusher'),
    ( 'PyCharm'),
    ( 'Pygame'),
    ( 'Pylint'),
    ( 'PyQT'),
    ( 'PySpark'),
    ( 'pytest'),
    ( 'Python'),
    ( 'PythonAnywhere'),
    ( 'Pytorch'),
    ( 'Qemu'),
    ( 'QnA Maker'),
    ( 'Qt'),
    ( 'Qt Creator'),
    ( 'QML (Qt Modeling Language)'),
    ( 'Qualaroo'),
    ( 'Quarkus'),
    ( 'Quartz (Scheduler)'),
    ( 'Quasar Framework'),
    ( 'Qubole'),
    ( 'QueryDSL'),
    ( 'QuickBlox'),
    ( 'Intuit QuickBooks'),
    ( 'Quill'),
    ( 'RabbitMQ'),
    ( 'Racket'),
    ( 'Rails Spring'),
    ( 'RailsAdmin'),
    ( 'RoR (Ruby on Rails)'),
    ( 'Ramda'),
    ( 'RAML'),
    ( 'Rancher'),
    ( 'Rasa NLU'),
    ( 'Raspberry Pi'),
    ( 'Ratchet'),
    ( 'React'),
    ( 'React Admin'),
    ( 'React Context'),
    ( 'React Helmet'),
    ( 'React Morph'),
    ( 'React Native'),
    ( 'React Native Firebase'),
    ( 'React Native Paper'),
    ( 'React Navigation'),
    ( 'React Redux'),
    ( 'React Router'),
    ( 'React Storybook'),
    ( 'React Testing'),
    ( 'React Hooks'),
    ( 'ReactiveX'),
    ( 'UI Kitten'),
    ( 'ReactorKit'),
    ( 'ReadMe.io'),
    ( 'Realm'),
    ( 'Recoil'),
    ( 'Red Hat Enterprise Linux'),
    ( 'Redash'),
    ( 'Redis'),
    ( 'Redmine'),
    ( 'Redux'),
    ( 'Redux-Saga'),
    ( 'Redux-Thunk'),
    ( 'Render'),
    ( 'RequireJS'),
    ( 'REST API'),
    ( 'REST-assured'),
    ( 'RethinkDB'),
    ( 'RingCentral'),
    ( 'RIOT (OS)'),
    ( 'Rocket'),
    ( 'RocketChat'),
    ( 'RocksDB'),
    ( 'Rollbar'),
    ( 'rollup.js'),
    ( 'RRDtool'),
    ( 'RTCMultiConnection'),
    ( 'RuboCop'),
    ( 'Ruby'),
    ( 'RubyMine'),
    ( 'RubyMotion'),
    ( 'Rundeck'),
    ( 'Rust'),
    ( 'RxJava'),
    ( 'RxJS'),
    ( 'RxKotlin'),
    ( 'RxSwift'),
    ( 'Amazon S3 Object Lambda'),
    ( 'Safari'),
    ( 'Sagui'),
    ( 'Sails.js'),
    ( 'Sailthru'),
    ( 'Salesforce Sales Cloud'),
    ( 'Saltstack'),
    ( 'Samsung ARTIK'),
    ( 'Sane Stack'),
    ( 'Sanic'),
    ( 'Sanity.io'),
    ( 'SASS (Syntactically Awesome Style Sheets)'),
    ( 'Sauce Labs'),
    ( 'SBT (Simple Build Tool)'),
    ( 'Scala'),
    ( 'Scala Native'),
    ( 'ScalaNLP'),
    ( 'Scaledrone'),
    ( 'Scaleway'),
    ( 'Scalr'),
    ( 'Scalyr'),
    ( 'Scikit-image'),
    ( 'Scikit-learn'),
    ( 'SciPy'),
    ( 'Scouter'),
    ( 'Scratch'),
    ( 'Screenful'),
    ( 'Screwdriver CD'),
    ( 'Scrutinizer CI'),
    ( 'SCSS (Sassy CSS)'),
    ( 'SDL (Simple DirectMedia Layer)'),
    ( 'Seaborn'),
    ( 'Searchify'),
    ( 'Searchkick'),
    ( 'SearchKit'),
    ( 'Security Monkey'),
    ( 'SeeVolution'),
    ( 'Seldon'),
    ( 'Selendroid'),
    ( 'Selenium'),
    ( 'Semantic UI'),
    ( 'Semantria API'),
    ( 'Sencha Touch'),
    ( 'SendBird'),
    ( 'SendHub'),
    ( 'Sendicate'),
    ( 'Sendwithus'),
    ( 'Sendy'),
    ( 'Sensu'),
    ( 'Sentry'),
    ( 'SEO4Ajax'),
    ( 'Sequel Pro'),
    ( 'Sequelize'),
    ( 'Serf'),
    ( 'SessionStack'),
    ( 'Shards'),
    ( 'Sheetlabs'),
    ( 'Sheetsee.js'),
    ( 'Sheetsu'),
    ( 'Shell Script'),
    ( 'Shields.io'),
    ( 'Shield UI'),
    ( 'Shinken'),
    ( 'Ship.js'),
    ( 'Shipit'),
    ( 'Shippo'),
    ( 'ShipStation'),
    ( 'Shipwire'),
    ( 'Shoutem'),
    ( 'Showdown'),
    ( 'ShutIt'),
    ( 'Sidekiq'),
    ( 'SignalR'),
    ( 'Simperium'),
    ( 'SFML (Simple and Fast Multimedia Library)'),
    ( 'SOAP (Simple Object Access Protocol)'),
    ( 'Simul Docs'),
    ( 'SimulationX'),
    ( 'Singer'),
    ( 'Sinon.JS'),
    ( 'Sitecake'),
    ( 'Siteleaf'),
    ( 'SiteMesh'),
    ( 'Sitespeed.io'),
    ( 'Sizzy'),
    ( 'Skaffold'),
    ( 'Sketch'),
    ( 'Sketchboard'),
    ( 'Skia'),
    ( 'Slaask'),
    ( 'Slack'),
    ( 'Slack API'),
    ( 'SlackTextViewController'),
    ( 'Slate'),
    ( 'Slick'),
    ( 'Slim'),
    ( 'Slim Lang'),
    ( 'Site.js'),
    ( 'Smartling'),
    ( 'SmartyStreets'),
    ( 'Sunshine Conversations'),
    ( 'SnapEngage'),
    ( 'SnapKit'),
    ( 'Snappykit'),
    ( 'SnapSearch'),
    ( 'Snowflake'),
    ( 'Snowplow'),
    ( 'Snyk'),
    ( 'Socket.IO'),
    ( 'SocketCluster'),
    ( 'SockJS'),
    ( 'Dassault Systemes SOLIDWORKS'),
    ( 'Solidity'),
    ( 'Sonarqube'),
    ( 'Sonatype Nexus'),
    ( 'Sourcegraph'),
    ( 'Sourcetrail'),
    ( 'Sourcetree'),
    ( 'Spacemacs'),
    ( 'SpaceVim'),
    ( 'Hootsuite'),
    ( 'SparkPost'),
    ( 'SpeedCurve'),
    ( 'Sphinx'),
    ( 'Spinnaker'),
    ( 'Spinnakr'),
    ( 'Splunk'),
    ( 'Spreedly'),
    ( 'Spring AMQP'),
    ( 'Spring Batch'),
    ( 'Spring Boot'),
    ( 'Spring Cloud'),
    ( 'Spring Cloud Spanner'),
    ( 'Spring CredHub'),
    ( 'Spring Data'),
    ( 'Spring Data JPA'),
    ( 'Spring Flo'),
    ( 'Spring for Apache Kafka'),
    ( 'Spring HATEOAS'),
    ( 'Spring Integration'),
    ( 'Spring LDAP'),
    ( 'Spring MVC'),
    ( 'Spring REST Docs'),
    ( 'Spring Roo'),
    ( 'Spring Security'),
    ( 'Spring Session'),
    ( 'Spring Shell'),
    ( 'Spring Statemachine'),
    ( 'Spring Tools (STS)'),
    ( 'Spring Vault'),
    ( 'SQL Tabs'),
    ( 'SQLAlchemy'),
    ( 'sqlDB'),
    ( 'SQLite'),
    ( 'SQLPad'),
    ( 'SQream DB'),
    ( 'Sqreen'),
    ( 'Squarespace'),
    ( 'Squid (Proxy Server)'),
    ( 'SSLMate'),
    ( 'StackBlitz'),
    ( 'Stackify'),
    ( 'StackStorm'),
    ( 'Starling (Library)'),
    ( 'Stashboard'),
    ( 'Statamic'),
    ( 'Statbot'),
    ( 'StatHat'),
    ( 'Statsbot'),
    ( 'StatsD'),
    ( 'StatusGator'),
    ( 'Status Ticker'),
    ( 'Status.io'),
    ( 'Statusbot'),
    ( 'StatusCake'),
    ( 'StatusPage.io'),
    ( 'Steamworks'),
    ( 'Stencil'),
    ( 'Stetho'),
    ( 'Stimulus'),
    ( 'Stongbox'),
    ( 'StopLight'),
    ( 'StoreMaven'),
    ( 'Storybook'),
    ( 'Strapi'),
    ( 'Streak'),
    ( 'Microsoft Stream'),
    ( 'Streem'),
    ( 'Strider CD'),
    ( 'Stripe'),
    ( 'SQL (Structured Query Language)'),
    ( 'StyleCI'),
    ( 'styled-components'),
    ( 'Stylus'),
    ( 'Sublime Text'),
    ( 'Apache Subversion (SVN)'),
    ( 'SugarCRM'),
    ( 'SUIT CSS'),
    ( 'SummitDB'),
    ( 'Sumo Logic'),
    ( 'SupportBee'),
    ( 'Enchant'),
    ( 'SupportYourApp'),
    ( 'Surfly'),
    ( 'SurveyJS'),
    ( 'Survicate'),
    ( 'Sush.io'),
    ( 'Svelte'),
    ( 'Swagger'),
    ( 'Swat.io'),
    ( 'SweetAlert'),
    ( 'Sweettracker API'),
    ( 'Swift'),
    ( 'Swift AI'),
    ( 'Swifton'),
    ( 'Swiftype'),
    ( 'Swiper.js'),
    ( 'Swrve'),
    ( 'SWT (Standard Widget Toolkit)'),
    ( 'Sybase IQ'),
    ( 'Symfony'),
    ( 'Sysdig'),
    ( 'TMAP API'),
    ( 'TablePlus'),
    ( 'Tabletop.js'),
    ( 'Tadpole DB Hub'),
    ( 'Tailwind CSS'),
    ( 'Talkdesk'),
    ( 'Tandem'),
    ( 'Tapcart'),
    ( 'Taplytics'),
    ( 'Targetprocess'),
    ( 'Taskulu'),
    ( 'tawkto.to'),
    ( 'TaxCloud'),
    ( 'TaxJar'),
    ( 'TeamCity'),
    ( 'TeamGrid'),
    ( 'Telegram'),
    ( 'Telegram Bot API'),
    ( 'Teletraan'),
    ( 'Teletype for Atom'),
    ( 'Temboo'),
    ( 'Templarbit'),
    ( 'Tendermint'),
    ( 'TensorFlow'),
    ( 'TensorFlow Lite'),
    ( 'TensorFlow.js'),
    ( 'Terraform'),
    ( 'Tesseract OCR'),
    ( 'Tesseract.js'),
    ( 'Test Kitchen'),
    ( 'Testdroid'),
    ( 'TestFairy'),
    ( 'TestFlight'),
    ( 'TestFX'),
    ( 'Testing Library'),
    ( 'TestingBot'),
    ( 'TestLodge'),
    ( 'TestRail'),
    ( 'Textadept'),
    ( 'Textscope'),
    ( 'Theano'),
    ( 'Eclipse Theia'),
    ( 'Three.js'),
    ( 'Thymeleaf'),
    ( 'Tibero'),
    ( 'TiDB'),
    ( 'TileStache'),
    ( 'Vector'),
    ( 'TimescaleDB'),
    ( 'Tinfoil Security'),
    ( 'Tipe'),
    ( 'Tkinter'),
    ( 'Toggl'),
    ( 'TokuMX'),
    ( 'Torbit'),
    ( 'Torch'),
    ( 'Tornado'),
    ( 'ToroDB'),
    ( 'TortoiseGit'),
    ( 'TortoiseSVN'),
    ( 'Torus Labs'),
    ( 'Toss API'),
    ( 'Tower'),
    ( 'TraceView'),
    ( 'TrackJS'),
    ( 'TradingView'),
    ( 'Traefik'),
    ( 'Trailblazzer'),
    ( 'TrailDB'),
    ( 'Trails'),
    ( 'trak.io'),
    ( 'Transifex'),
    ( 'Transloadit'),
    ( 'Travis CI'),
    ( 'Treasure Data'),
    ( 'Trello'),
    ( 'TRIBON'),
    ( 'Trigger.io'),
    ( 'TrueVault'),
    ( 'Arm TrustZone'),
    ( 'Arm The TrustZone API'),
    ( 'Tsuru'),
    ( 'tus.io'),
    ( 'twemproxy'),
    ( 'Twilert'),
    ( 'Twilio'),
    ( 'Twilio Functions'),
    ( 'Twilio SendGrid'),
    ( 'Twist'),
    ( 'Twisted'),
    ( 'Twitch API'),
    ( 'Twitter API'),
    ( 'Tyk API Gateway'),
    ( 'Tyk Cloud'),
    ( 'Typeform'),
    ( 'Adobe Fonts'),
    ( 'TypeORM'),
    ( 'Typescript'),
    ( 'UAParser.js'),
    ( 'Uber Open Source'),
    ( 'Ubuntu'),
    ( 'Udash'),
    ( 'UFW (Uncomplicated Firewall)'),
    ( 'UglifyJS'),
    ( 'UIKit'),
    ( 'Ultralight'),
    ( 'Unbabel'),
    ( 'Unbounce'),
    ( 'Underscore.js'),
    ( 'ungit'),
    ( 'UniRx'),
    ( 'unistore'),
    ( 'Unito'),
    ( 'Unity'),
    ( 'Unity ML-Agents'),
    ( 'Unix'),
    ( 'Unreal Engine'),
    ( 'Upbit API'),
    ( 'updown.io'),
    ( 'Uploadcare'),
    ( 'Uppy'),
    ( 'Upsource'),
    ( 'Uptime Robot'),
    ( 'Airship'),
    ( 'URL2PNG'),
    ( 'Urwid'),
    ( 'Userbin'),
    ( 'Usersnap'),
    ( 'UserTesting'),
    ( 'UserVoice'),
    ( 'Usetrace'),
    ( 'uWSGI'),
    ( 'UXCam'),
    ( 'UXPin'),
    ( 'Vaadin'),
    ( 'VAddy'),
    ( 'Vagrant'),
    ( 'Vagrant Cloud'),
    ( 'Valhalla'),
    ( 'Vanilla.JS'),
    ( 'Vapor'),
    ( 'Varnish'),
    ( 'HashiCorp Vault'),
    ( 'Visual Basic .NET (VB.NET)'),
    ( 'Microsoft Visual Basic Script (VBScript)'),
    ( 'Veneur'),
    ( 'Venom'),
    ( 'Veriff'),
    ( 'Verilog'),
    ( 'Vert.x'),
    ( 'Vespa'),
    ( 'Vessel'),
    ( 'VHDL (VHSIC Hardware Description Language)'),
    ( 'VIBE (Video Inference for Human Body Pose and Shape Estimation)'),
    ( 'Splunk On-Call'),
    ( 'Victory'),
    ( 'Vidyard'),
    ( 'GoView'),
    ( 'Vim'),
    ( 'Vim Python IDE'),
    ( 'VimR'),
    ( 'ViralSweep'),
    ( 'Virgil Security'),
    ( 'VirtKick'),
    ( 'virtual-dom'),
    ( 'VirtualBox'),
    ( 'VirusTotal API (VT API)'),
    ( 'Microsoft Visual Basic for Applications (VBA)'),
    ( 'Microsoft Visual Studio'),
    ( 'Microsoft Visual Studio Code (VSCode)'),
    ( 'Microsoft Visual Studio Live Share'),
    ( 'VWO (Visual Website Optimizer)'),
    ( 'VisualOps'),
    ( 'VisualPing'),
    ( 'VividCortex'),
    ( 'VMware'),
    ( 'VMware Horizon'),
    ( 'VMware vSphere'),
    ( 'Volleyy'),
    ( 'Volt'),
    ( 'Voxlmplant'),
    ( 'Vue CLI'),
    ( 'V-Model'),
    ( 'VueStrap'),
    ( 'Vuetify'),
    ( 'vuex'),
    ( 'Vuforia'),
    ( 'Vultr'),
    ( 'Vundle'),
    ( 'vx'),
    ( 'Vyte'),
    ( 'Wagtail'),
    ( 'WakaTime'),
    ( 'WalkMe'),
    ( 'WMS (Warehouse Management System)'),
    ( 'Watchsend'),
    ( 'WDF (Window Driver Frameworks)'),
    ( 'Weave'),
    ( 'Web SDK'),
    ( 'web3.js'),
    ( 'Web3.py'),
    ( 'web3j'),
    ( 'WebEngage'),
    ( 'Webex'),
    ( 'Webflow'),
    ( 'WebGazer'),
    ( 'WebGL'),
    ( 'WebGPU'),
    ( 'WebKit'),
    ( 'Webpack'),
    ( 'Webpacker'),
    ( 'WebStorm'),
    ( 'WebtoB'),
    ( 'WebTranslateIt'),
    ( 'WeChat'),
    ( 'Weex'),
    ( 'Wekan'),
    ( 'WePay'),
    ( 'wercker'),
    ( 'Wildfly'),
    ( 'Willow'),
    ( 'WinAPI (Windows API)'),
    ( 'Microsoft Windows IoT'),
    ( 'Windows Forms'),
    ( 'Windows Kernel'),
    ( 'Microsoft Windows Server'),
    ( 'Microsoft Windows Server Update Services (WSUS)'),
    ( 'winjs'),
    ( 'WinPcap'),
    ( 'Wireshark'),
    ( 'wise.io'),
    ( 'Wistia'),
    ( 'wit.ai'),
    ( 'Wix'),
    ( 'Wombat'),
    ( 'WooCommerce'),
    ( 'Woopra'),
    ( 'WordMove'),
    ( 'WordPress'),
    ( 'Working Copy'),
    ( 'WOVN.io'),
    ( 'Wowza'),
    ( 'WP Engine'),
    ( 'WSGI (Web Server Gateway Interface)'),
    ( 'Wufoo'),
    ( 'Xamarin'),
    ( 'Xamarin Test Cloud'),
    ( 'XAML'),
    ( 'Xcessiv'),
    ( 'Xcode'),
    ( 'Xen'),
    ( 'Xero'),
    ( 'XGBoost'),
    ( 'Xltrail'),
    ( 'xlwings'),
    ( 'NocoDB'),
    ( 'Xplatform'),
    ( 'Xplenty'),
    ( 'XpressEngine'),
    ( 'Xtext'),
    ( 'YAML (YAML Ain''t Markup Language)'),
    ( 'Yammer'),
    ( 'Yara'),
    ( 'Yarn'),
    ( 'Yeoman'),
    ( 'Yesod'),
    ( 'Yew'),
    ( 'Yii'),
    ( 'Yottaa'),
    ( 'YouTrack'),
    ( 'Zabbix'),
    ( 'Zapier'),
    ( 'Zappa'),
    ( 'Zen Rails Base Application'),
    ( 'Zencoder'),
    ( 'Laminas'),
    ( 'Zendesk'),
    ( 'Zenefits'),
    ( 'ZenHub'),
    ( 'Zephyr'),
    ( 'Zeplin'),
    ( 'ZeroMQ'),
    ( 'ZeroVM'),
    ( 'Zest'),
    ( 'zetcd'),
    ( 'ZingChart'),
    ( 'Zipkin'),
    ( 'Zoom'),
    ( 'Zube'),
    ( 'Zulip'),
    ( 'Zuora'),
    ( 'Zurb'),
    ( 'Zxing'),
    ( 'λ Gordon'),
    ( 'Kids Note'),
    ( 'Windows Sandbox'),
    ( 'Scout-App'),
    ( 'GuardRail'),
    ( 'Shogun'),
    ( 'HPE Helion OpenStack'),
    ( 'Kontena Pharos'),
    ( 'insightsoftware'),
    ( 'Amazon OpenSearch Service'),
    ( 'Azure Data Studio'),
    ( 'Front Scheduling'),
    ( 'Adobe Acrobat'),
    ( 'Adobe FrameMaker (Fm)'),
    ( 'ANSYS FLUENT'),
    ( 'Apple Keynote'),
    ( 'Autodesk AutoCAD Civil 3D'),
    ( 'Bentley MicroStation'),
    ( 'Cadence PSpice'),
    ( 'COMSOL Multiphysics'),
    ( 'Container Linux(CoreOS Container Linux)'),
    ( 'Corel CorelDraw Graphics Suite'),
    ( 'Dassasult Systemes Abaqus'),
    ( 'EMR (Electronic medical record)'),
    ( 'FileMaker Pro'),
    ( 'GNU Octave'),
    ( 'Hewlett Packard HP-UX'),
    ( 'Hewlett Packard LoadRunner'),
    ( 'IBM Cognos Impromptu'),
    ( 'Leica Geosystems ERDAS IMAGINE'),
    ( 'Marketo Marketing Automation'),
    ( 'MathWorks Simulink'),
    ( 'Microsoft Dynamics'),
    ( 'Microsoft Project'),
    ( 'Microsoft Publisher'),
    ( 'Microsoft Visio'),
    ( 'MicroStrategy'),
    ( 'Minitab'),
    ( 'Moodle'),
    ( 'MSC Software Adams'),
    ( 'MSC Software Nastran'),
    ( 'Oracle Hyperion'),
    ( 'Oracle Taleo'),
    ( 'PTC Mathcad'),
    ( 'PWA Builder'),
    ( 'QlikView'),
    ( 'ReliaSoft Weibull++ 6'),
    ( 'SingleStore'),
    ( 'Solid Edge'),
    ( 'StataCorp Stata'),
    ( 'Teradata'),
    ( 'Veritas NetBackup'),
    ( 'Wolfram Mathematica'),
    ( '.NET Core'),
    ( '.NET Framework'),
    ( 'Adobe Dimension'),
    ( 'Dash for macOS'),
    ( 'iOS SDK'),
    ( 'Kraken'),
    ( 'Lyft'),
    ( 'Google Material Design'),
    ( 'matter.js'),
    ( 'Meta'),
    ( 'Microsoft Windows SDK'),
    ( 'MySQL Query Analyzer'),
    ( 'NVIDIA Morpheus'),
    ( 'Open MPI'),
    ( 'Roblox'),
    ( 'Rocket Software'),
    ( 'ROOM (Real Time Object Oriented Modeling)'),
    ( 'Spotify');

update skill set created_date = now()
where skill_id > 0;